Removed garbage from copy&paste

diff --git a/attach b/attach
--- a/attach
+++ b/attach
@@ -5,9 +5,9 @@ session=${1//@(.|\/)}
 
 tmux has-session -t "$session" 2>/dev/null
 if [ $? != 0 ]; then
-    if [ $force ]; then
-        tmux attach -t "$session"
-    else
-        echo "ERROR: Server $session not running"
-    fi
+    echo "Attaching to session $session"
+    tmux attach -t "$session"
+else
+    echo "ERROR: Server $session not running"
+    exit 1
 fi
